spring:
  application:
    name: load-balancer

loadbalancer:
  strategy: leastConnections

  servers:
  - name: A
    url: http://localhost:8081
    weight: 2

  - name: B
    url: http://localhost:8082
    weight: 1

  - name: C
    url: http://localhost:8083
    weight: 2
