spring:
  application:
    name: load-balancer

loadbalancer:
  strategy: ipHash

  servers:
  - name: A
    url: http://localhost:8081
    weight: 9

  - name: B
    url: http://localhost:8082
    weight: 5

  - name: C
    url: http://localhost:8083
    weight: 3
